import simpleGit, { SimpleGit } from 'simple-git';
import { Octokit } from '@octokit/rest';
import path from 'path';
import fs from 'fs';
import { execSync } from 'child_process';
import chalk from 'chalk';

export interface PackageBumpInfo {
  name: string;
  oldVersion: string;
  newVersion: string;
}

export interface PRDetails {
  packageName?: string;
  oldVersion?: string;
  newVersion?: string;
  packages?: PackageBumpInfo[];
  branchName: string;
  breakingChangeAnalysis: string;
  explanation: string;
  testEvidence: string;
  remediatedFiles: string[];
}

export interface PRResult {
  success: boolean;
  pullRequestUrl?: string;
  branchName: string;
  commitHash?: string;
  diffSummary?: string;
  mode: 'github-live' | 'local-simulated';
}

function isValidGitHubToken(token?: string): boolean {
  if (!token) return false;
  const t = token.trim();
  if (t.length < 20) return false;
  if (t.startsWith('your_') || t.includes('token_here')) return false;
  return true;
}

export class GitManager {
  private targetDir: string;
  private git: SimpleGit;
  private octokit?: Octokit;
  private githubToken?: string;
  private repoOwner?: string;
  private repoName?: string;

  constructor(targetDir: string) {
    this.targetDir = path.resolve(targetDir);
    this.git = simpleGit({ baseDir: this.targetDir });
    this.githubToken = process.env.GITHUB_TOKEN;
    this.repoOwner = process.env.REPO_OWNER;
    this.repoName = process.env.REPO_NAME;

    if (isValidGitHubToken(this.githubToken)) {
      this.octokit = new Octokit({ auth: this.githubToken });
    }
  }

  public async ensureRemoteOrigin(): Promise<void> {
    if (!this.githubToken || !this.repoOwner || !this.repoName) return;
    const authRemoteUrl = `https://x-access-token:${this.githubToken}@github.com/${this.repoOwner}/${this.repoName}.git`;
    try {
      const remotes = await this.git.getRemotes(true);
      const origin = remotes.find((r) => r.name === 'origin');
      if (origin) {
        await this.git.remote(['set-url', 'origin', authRemoteUrl]);
      } else {
        await this.git.addRemote('origin', authRemoteUrl);
      }
    } catch {
      // ignore
    }
  }

  public async ensureGitRepo(): Promise<void> {
    const isRepo = await this.git.checkIsRepo();
    const authorName = process.env.GIT_AUTHOR_NAME || 'Hefaetus Agent';
    const authorEmail = process.env.GIT_AUTHOR_EMAIL || 'hefaetus-agent@users.noreply.github.com';

    if (!isRepo) {
      await this.git.init();
      await this.git.addConfig('user.name', authorName);
      await this.git.addConfig('user.email', authorEmail);
      await this.git.add('.');
      await this.git.commit('chore: initial repository baseline');
      await this.git.branch(['-M', 'main']);
    } else {
      try {
        await this.git.addConfig('user.name', authorName);
        await this.git.addConfig('user.email', authorEmail);
      } catch {
        // ignore
      }
    }
  }

  public async prepareRemediationBranch(branchName: string): Promise<void> {
    await this.ensureGitRepo();
    try {
      await this.git.checkout('main');
    } catch {
      try {
        await this.git.raw(['checkout', '-f', 'main']);
      } catch {
        // ignore
      }
    }

    const branchSummary = await this.git.branchLocal();
    if (branchSummary.all.includes(branchName)) {
      try {
        await this.git.deleteLocalBranch(branchName, true);
        await this.git.checkoutLocalBranch(branchName);
      } catch {
        await this.git.checkout(branchName);
        await this.git.raw(['reset', '--hard', 'main']);
      }
    } else {
      await this.git.checkoutLocalBranch(branchName);
    }
  }

  public async commitChanges(
    message: string,
    files: string[]
  ): Promise<string> {
    await this.ensureGitRepo();
    for (const f of files) {
      const fullPath = path.join(this.targetDir, f);
      if (fs.existsSync(fullPath)) {
        await this.git.add(f);
      }
    }
    const commitResult = await this.git.commit(message);
    return commitResult.commit || 'HEAD';
  }

  public generatePRBody(details: PRDetails): string {
    let summarySection = '';
    if (details.packages && details.packages.length > 0) {
      summarySection = `This automated pull request was generated by **Hefaetus** to remediate security vulnerabilities and resolve breaking changes across the following dependencies:\n\n` +
        details.packages.map((p) => `- **\`${p.name}\`**: \`${p.oldVersion}\` ➔ \`${p.newVersion}\``).join('\n');
    } else {
      summarySection = `This automated pull request was generated by **Hefaetus** to remediate security risks and resolve breaking changes introduced by updating \`${details.packageName}\` from \`${details.oldVersion}\` to \`${details.newVersion}\`.`;
    }

    return `## 🛡️ Hefaetus Autonomous Dependency Remediation

### 📌 Summary
${summarySection}

---

### 💥 Breaking Change Root Cause Analysis
${details.breakingChangeAnalysis}

---

### 🛠️ Automated Code Remediation
${details.explanation}

**Remediated Call-Sites:**
${details.remediatedFiles.map((f) => `- \`${f}\``).join('\n')}

---

### 🧪 Verification & Test Evidence
The automated remediation loop verified that unit and integration tests pass inside an isolated container sandbox:

\`\`\`text
${details.testEvidence.trim()}
\`\`\`

---

### 📋 Reviewer Checklist
- [x] Dependencies upgraded in \`package.json\` to secure target versions.
- [x] Breaking API calls refactored to modern standards.
- [x] Test suite passing 100% in isolated container sandbox.
- [ ] Manual review and approval by repository maintainer.

> *Created with ❤️ by **Hefaetus Autonomous DevSecOps Agent**.*
`;
  }

  public async getDiff(): Promise<string> {
    try {
      const diff = await this.git.diff(['main']);
      if (diff && diff.trim().length > 0) {
        return diff;
      }
    } catch {
      // fallback
    }

    try {
      return await this.git.diff(['HEAD~1']);
    } catch {
      return await this.git.diff();
    }
  }

  public async createOrSimulatePR(details: PRDetails): Promise<PRResult> {
    const diffSummary = await this.getDiff();
    const pkgDesc = details.packages && details.packages.length > 0
      ? details.packages.map(p => `${p.name}@${p.newVersion}`).join(', ')
      : `${details.packageName}@${details.newVersion}`;
    const title = `fix(deps): remediate breaking changes for ${pkgDesc} upgrade`;
    const prBody = this.generatePRBody(details);

    const hasLiveCreds =
      Boolean(this.octokit) &&
      Boolean(this.repoOwner) &&
      Boolean(this.repoName) &&
      this.repoOwner !== 'your_github_username_or_org' &&
      this.repoName !== 'mock-target-app';

    if (hasLiveCreds && this.octokit && this.repoOwner && this.repoName) {
      try {
        await this.ensureRemoteOrigin();
        console.log(`Pushing branch ${details.branchName} to GitHub remote...`);
        await this.git.push('origin', details.branchName, ['--set-upstream', '--force']);
        console.log(`✔ Branch ${details.branchName} successfully pushed to GitHub!`);

        let prUrl: string | undefined;
        let commitHash: string | undefined;

        try {
          const prResponse = await this.octokit.pulls.create({
            owner: this.repoOwner,
            repo: this.repoName,
            title,
            head: details.branchName,
            base: 'main',
            body: prBody,
          });
          prUrl = prResponse.data.html_url;
          commitHash = prResponse.data.head.sha;
        } catch (prErr: any) {
          if (prErr.status === 422) {
            const existing = await this.octokit.pulls.list({
              owner: this.repoOwner,
              repo: this.repoName,
              head: `${this.repoOwner}:${details.branchName}`,
              state: 'open',
            });
            if (existing.data.length > 0) {
              prUrl = existing.data[0].html_url;
              commitHash = existing.data[0].head.sha;
              await this.octokit.pulls.update({
                owner: this.repoOwner,
                repo: this.repoName,
                pull_number: existing.data[0].number,
                body: prBody,
              });
            } else {
              throw prErr;
            }
          } else if (prErr.status === 403) {
            // Attempt GitHub CLI (gh) fallback
            try {
              console.log('Attempting PR creation via GitHub CLI (gh pr create)...');
              const tmpBodyFile = path.join(this.targetDir, '.pr_body.tmp.md');
              fs.writeFileSync(tmpBodyFile, prBody, 'utf8');
              const ghOutput = execSync(
                `gh pr create --repo "${this.repoOwner}/${this.repoName}" --base main --head "${details.branchName}" --title "${title}" --body-file "${tmpBodyFile}"`,
                {
                  env: { ...process.env, GH_TOKEN: this.githubToken },
                  encoding: 'utf8',
                }
              );
              try { fs.unlinkSync(tmpBodyFile); } catch {}
              const lines = ghOutput.trim().split('\n');
              prUrl = lines[lines.length - 1].trim();
            } catch (ghError: any) {
              throw prErr;
            }
          } else {
            throw prErr;
          }
        }

        return {
          success: true,
          pullRequestUrl: prUrl,
          branchName: details.branchName,
          commitHash,
          diffSummary,
          mode: 'github-live',
        };
      } catch (error: any) {
        console.warn(
          chalk.red(
            `\n⚠️  [GitManager Warning] Live GitHub API call failed (${error.message}).`
          )
        );
        if (error.message?.includes('not permitted to create or approve pull requests') || error.status === 403) {
          console.warn(
            chalk.yellow(
              `\n💡 HOW TO ENABLE PULL REQUESTS ON GITHUB:\n` +
              `   1. Go to: https://github.com/${this.repoOwner}/${this.repoName}/settings/actions\n` +
              `   2. Under "Workflow permissions", select "Read and write permissions"\n` +
              `   3. CHECK: "Allow GitHub Actions to create and approve pull requests"\n` +
              `   4. Click Save.\n` +
              `   (Alternatively, provide a Personal Access Token as 'GH_PAT' secret in GitHub Secrets).\n`
            )
          );
        }
      }
    }

    const simulatedUrl = `https://github.com/${this.repoOwner || 'demo-org'}/${this.repoName || 'target-app'}/pull/1`;

    return {
      success: true,
      pullRequestUrl: simulatedUrl,
      branchName: details.branchName,
      diffSummary,
      mode: 'local-simulated',
    };
  }
}
